#ifndef SERVER_CONN_HH
#define SERVER_CONN_HH
#include <stdint.h>
#include <vector>
#include "common.hh"

struct Conn {
  int fd = -1;
  // application's intention, for the event loop
  bool want_read = false;
  bool want_write = false;
  bool want_close = false;
  // buffered input and output
  Buffer incoming;  // data to be parsed by the application
  Buffer outgoing;  // responses generated by the application
};

// Server-side connection management APIs
Conn *handle_accept(int fd);
bool try_process_one_request(Conn *conn);
void handle_write(Conn *conn);
void handle_read(Conn *conn);

#endif